### ISSUE TITLE
Unexpected errors: Enrollment Crosses Participating End; Enrollment Crosses Operating End; Project Exit Before Start

### ISSUE THREAD

**Issue by kaitlit** [abtassociates/eva#428]
**Describe the bug**
We have encountered errors in Eva that do not appear to be reflective of the data in the csv export. Specifically, we are seeing 3 errors that don't match the data in the CSV.

Error: Enrollment Crosses Participating End - the enrollments that are identified as errors are for projects that do not have Participation End Dates. We have confirmed the csv accurately reflects what is in HMIS and does not have an end date.

Error: Enrollment Crosses Operating End - the enrollments that are identified as errors are for projects that do not have Operating End Dates. We have confirmed the csv accurately reflects what is in HMIS and does not have an end date.

Error: Enrollment Crosses Operating End - the enrollments that are identified as errors are for projects that do not have Operating End Dates. We have confirmed the csv accurately reflects what is in HMIS and does not have an end date.

Error: Project Exit Before Start - the enrollments that are identified have project exit dates that fall after project start dates. We have confirmed that the csv accurately reflects what is in HMIS and the dates are in a logical order.

**To Reproduce**
Without uploading data, I don't know that I can indicate steps to reproduce the behavior.

**Expected behavior**
We do not expect to see errors related to Operating or Participating End dates for enrollments into projects that do not have such end dates. 
We do not expect to see errors related to project exit before start date when the dates in the csv reflect project start before project exit.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Operating System: Windows 10 64-bit
 - Browser: [What is my browser? Edge 119 on Windows 10

**Additional context**
We have already contacted our vendor who confirmed the csv is working as expected and suggested we reach out here.

**Comment by kiadso** [comment]
Hi @kaitlit,

What is the date range you are using to run your HMIS CSV Export? We are working on a fix for this issue, but in the meantime, it may have something to do with that.

Thanks-
Genelle

**Comment by kaitlit** [comment]
Ah, I'm sorry I didn't include it. The report period was FY23 - 10/1/2022 through 9/30/2023.

**Comment by kiadso** [comment]
It's all good- can you try rerunning it for 10/1/2022 through today and see if you get the same problem? If you do (and even if you don't), hang on til tomorrow, we are pushing some fixes through that would affect this. 
This isn't to say you should not make your export end date in the past; just as a workaround, try making it today until we have pushed the fix.

**Comment by kaitlit** [comment]
That was it - just ran it for 10/1/2022 through today and we do not get those errors. Looking forward to seeing the fixes tomorrow. Thanks!

**Comment by kiadso** [comment]
Hi @kaitlit 
Eva has been updated, but the more I think about it, your issue may not have been addressed exactly. Could you try it again through FY23 and just let me know if the problem's still there?

**Comment by kaitlit** [comment]
You are correct, those errors are still erroneously appearing when I run for FY23.

In re-running it, I encountered a different issue - a High Priority structural issue on Data Type. Detail: In the Client file, the AdditionalRaceEthnicity column should have a data type of integer but in this file, it is string.

In the Data Standards, that element is a string, and I checked the CSV specs and if I'm understanding correctly, the expected data type is S100 - a string up to 100 characters. 

Can you advise on both issues? Thank you!

**Comment by kiadso** [comment]
Yes, we just now pushed the fix for the data type issue. Thanks for your patience on this point. 

We are doing a more thorough review of dates in Eva and will likely have a broader push across several date points by Thursday of next week that should take care of your original issues. Til then, continue to run your file through "today."

Thanks again for your patience!

**Comment by kiadso** [comment]
Hi @kaitlit 

The fix for the "Enrollment Crosses..." issues was pushed to Eva today. Thanks again for the report and please reopen this issue if you're not seeing that it's resolved!
