### ISSUE TITLE
EVA Upload Error

### ISSUE THREAD

**Issue by Phil-HF** [abtassociates/eva#535]
![DDI EVA Error](https://github.com/user-attachments/assets/8bd8de47-2095-4a09-aec8-44b8ec7b83b8)

The attached export file is throwing the attached error upon upload.

**Comment by kiadso** [comment]
Hi @Phil-HF,
I edited your Issue to remove the link you included to download your zip file since this is a public forum. Please follow whatever protocols you have on your side to address this data being shared in this way.
You likely have an impermissible character in your file. We are going to be updating Eva soon to catch these things differently. Watch for our next update.

**Comment by kiadso** [comment]
@Phil-HF can you email me at genelle.denzin at abtglobal dot com?

Thank you,
Genelle

**Comment by kiadso** [comment]
Hi @Phil-HF ,
Can you let us know the approximate date/time you uploaded to Eva so we can try to start troubleshooting your crash? If you don't know, can you upload again and if you get the crash, let us know when you uploaded?
Thanks!

**Comment by Phil-HF** [comment]
I just tried and saw the error.

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by alex-silverman** [comment]
Thank you for letting us know. We will take a closer look at the logs around that time to dig into this. By the way, did you happen to see this pop-up after your file started uploading?

![image](https://github.com/user-attachments/assets/03d35a30-3159-4f56-950f-543223e6b508)

**Comment by kiadso** [comment]
Hi @Phil-HF 
We can see a session where your file crashed, then a subsequent session where you uploaded successfully. What is the difference between the first file and the second one?

**Comment by Phil-HF** [comment]
I did not see the impermissible characters error. I only saw the Eva crashed error I submitted with the ticket.

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by Phil-HF** [comment]
Hi Genelle,
I just saw this same error for a different export for a different set of programs.

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by kiadso** [comment]
Hi @Phil-HF,
Can you try to upload again and tell me if anything changed? We updated Eva this week and it's possible your issue was resolved.

**Comment by kiadso** [comment]
Hi @Phil-HF,

If you are still getting the same problem, could you check the following files and tell me if any of them do NOT have 15 columns?

- CEParticipation
- EmploymentEducation
- Event
- ProjectCoC

If any of them do not have 15 columns, can you send the list of column names (column names only) that are in the file? Thank you!

-Eva dev team

**Comment by Phil-HF** [comment]
I’m still seeing the error:
***@***.***

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by kiadso** [comment]
Ok, thanks for letting us know!

Could you check the following files and tell me if any of them do NOT have 15 columns?

- CEParticipation
- EmploymentEducation
- Event
- ProjectCoC

If any of them do not have 15 columns, can you send the list of column names (column names only) that are in the file? Thank you!

-Eva dev team

**Comment by Phil-HF** [comment]
They all would seem to have 15 columns.

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by kiadso** [comment]
Hi @Phil-HF,
Can you try uploading again? We just made a major update to Eva that may or may not have addressed the issue here. Thank you so much for your patience!
Eva dev team

**Comment by Phil-HF** [comment]
I’m still seeing this:
***@***.***

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by kiadso** [comment]
Hi Phil! Thanks for your time and for calling me so we could trace down what may be the cause in real time with you. This response is to document the information I gathered on the call that may be of help in resolving the issue. In the meantime, we did arrive at a workaround: for you to run these two organizations along with other organizations in your CoC yourself and send these organizations their files.
Here are the things we learned on the call:

- Phil tasks his organizations to run their own exports to upload to Eva so they can get their own export files. Two of his organizations experience crashes whenever they upload.
- Organization A only has 1 project that is a Street Outreach project and Organization B has 3 projects, all are Homelessness Prevention.
- Phil tried running Organization A along with some other Organizations that he knows their export does work in the same export and that upload did NOT crash.
- This tells me Eva is expecting something that doesn't exist in the outreach export that does exist in other organizations' exports.

I checked the log for the staging site for when Phil said he uploaded one of his crashing exports.
- The log I see when Phil tried uploading to staging said: `Warning: Error in paste: cannot coerce type 'closure' to vector of type 'character'
  1: runApp [/tmp/RtmpFvWX8N/R.INSTALL107c63701be3/shiny/R/runapp.R#388]`

So while we look into what could be happening, Phil will run these Organizations together with other ones to get the files he needs.

Thanks all!

**Comment by alex-silverman** [comment]
Hi @Phil-HF,

In order to further look into the source of the problem, would you be willing to re-upload one of your files that leads to a crash on the same temporary testing site you used with @kiadso? The log issue referenced above was a simple code bug that I've fixed, so another upload should give us a better sense of the location of the source problem.

Alex

**Comment by Phil-HF** [comment]
I just tried uploading: 12:43pm 10/28/2024.

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by alex-silverman** [comment]
Hi @Phil-HF - thanks for the quick response. I've made a small update. Would you be willing to try one more time?

**Comment by Phil-HF** [comment]
I just did. 1:30pm 10/28.

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by alex-silverman** [comment]
Excellent. I see the problem is somewhere in the ProjectCoC.csv file. Would you be able to either re-upload or confirm that the columns in your ProjectCoC file are:

Column Name | Type
-- | --
ProjectCoCID | character
ProjectID | character
CoCCode | character
Geocode | character
Address1 | character
Address2 | character
City | character
State | character
ZIP | character
GeographyType | numeric
DateCreated | datetime
DateUpdated | datetime
UserID | character
DateDeleted | datetime
ExportID | character

**Comment by Phil-HF** [comment]
Unless I’m missing something, they match:

ProjectCoCID
ProjectID
CoCCode
Geocode
Address1
Address2
City
State
ZIP
GeographyType
DateCreated
DateUpdated
UserID
DateDeleted
ExportID
1132
889
TX-600
481338
1401 Elm St. #200
Dallas
TX
75202
1
2/7/2023 14:15
4/5/2024 18:28
A4T
E1707868800000


PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by alex-silverman** [comment]
Hi @Phil-HF - I think the problem may be the "#" in that address field. Eva should be able to handle that, but it might not be doing so correctly right now. I will look into implementing a fix for this asap.

**Comment by Phil-HF** [comment]
Yep. That would seem to be the culprit. Thank you.

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by alex-silverman** [comment]
I've tried implementing a fix in the test app if you have a moment to re-upload again.

**Comment by alex-silverman** [comment]
Glad to hear it. Thank you so much for your patience in troubleshooting the issue. I'm glad we got to the bottom of it. I will close this issue now and will be pushing a fix to Eva in the coming days.

**Comment by Phil-HF** [comment]
Thanks so much for your help!

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by alex-silverman** [comment]
@Phil-HF - Just wanted to confirm here that we have pushed the hotfix for this in Eva!

**Comment by Phil-HF** [comment]
It looks like it’s working. Thank you.

PHIL FORCE
HE/HIM
HMIS Administrator
M: 214.790.3238
3000 PEGASUS PARK DRIVE STE. 1020 | DALLAS, TX 75247
HOUSINGFORWARDNTX.ORG<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.housingforwardntx.org%2f&c=E,1,COmRqfiUlAc_b6tNDxPc7GAK50x84YN6ug0bBdIR0w7uWmNgHwKYZ0SjBP1oPpKqnHZ1Gwq1Rz8Gh5-i_rlnAB_JC38kcKWFiXN09a5UXlETtxJW&typo=1>
***@***.***<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhousingforwardntx.org%2f&c=E,1,LqAueXOSSYDLAEQGxtztxdtnjYpeFZxfJVcLxgcZTB4lZSr-NCFBrZcIQflkrzZsvvoyZHjidjeu-qBnSLGqsskFl5WfwoOFmAKpzOcljFfR&typo=1>
[facebook icon]<https://www.facebook.com/MDHADallas/>[linkedin icon]<https://www.linkedin.com/company/391873/admin/>

This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate, or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.
